### ISSUE TITLE
Is nitransforms now a full replacement for c3d_affine_tool?

### ISSUE THREAD

**Issue by effigies** [nipy/nitransforms#183]
Is nitransforms up to the task of replacing `c3d_affine_tool` at this point? This is a minor pain point in building Docker images, as the official package is large and hosted on sourceforge, the conda-forge package has a competing libitk dependency with ANTs. As far as I can tell, the only things it buys us are the ability to convert from FSL or ITK .mat files to ITK text affines, both of which nitransforms does.

Are the tests complete enough to go ahead and pull the trigger, or is there an issue tracking what remains to be done?

**Comment by oesteban** [comment]
Ready to pull the trigger :)

**Comment by effigies** [comment]
Awesome!
