### ISSUE TITLE
Implement "low memory" mode in ``apply()``

### ISSUE THREAD

**Issue by oesteban** [nipy/nitransforms#218]
We are currently propagating the ArrayProxy reported dtype unless an explicit output_dtype is set.

It would be more efficient to allow the user set a low memory flag such that the data type's itemsize is capped (e.g., float64 is cast into float32 and int64 into int32).

By performing the casting operation at access time, we would be sparing some memory (if I'm not wrong), especially when we arrive at map_coordinates.

WDTY @effigies? what would be an efficient way of capping the itemsize that works generically for any dtype?

**Comment by effigies** [comment]
Maybe something like:

```Python
def cap_dtype(dt, nbytes):
    return np.dtype(f'{dt.byteorder}{dt.kind}{min(nbytes, dt.itemsize)}')
```

```python
In [1]: import numpy as np

In [2]: def cap_dtype(dt, nbytes):
   ...:     return np.dtype(f'{dt.byteorder}{dt.kind}{min(nbytes, dt.itemsize)}')
   ...: 

In [3]: cap_dtype(np.dtype('f8'), 4)
Out[3]: dtype('float32')

In [4]: cap_dtype(np.dtype('f8'), 16)
Out[4]: dtype('float64')

In [5]: cap_dtype(np.dtype('i1'), 4)
Out[5]: dtype('int8')

In [6]: cap_dtype(np.dtype('i8'), 4)
Out[6]: dtype('int32')
```
