### ISSUE TITLE
Guess ITK-type with extension on load: ``.tfm``, ``.mat``, ``.h5``

### ISSUE THREAD

**Issue by oesteban** [nipy/nitransforms#87]
Permit calling `load` without `fmt` argument and still use the right loader.

**Comment by effigies** [comment]
I think `.mat` is also common for FSL and SPM affines, so I would have a look at:

https://github.com/nipy/nibabel/blob/65d5fc61545f55a50a45a07fbbaeb99c2dbe6bbb/nibabel/loadsave.py#L48-L53

Each class can provide a method:

```Python
def path_maybe_image(cls, fname, sniff=None):
    if sniff is None or len(sniff) < cls.sniff_size:
        with open(fname, 'rb') as fobj:
            sniff = fobj.read(cls.sniff_size)
    is_valid = ... # some check
    return is_valid, sniff
```

It defines a `sniff_size` class variable and some criterion to determine whether it's valid.
